CREATE TABLE reviewstream_reviews (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES reviewstream_users(id) ON DELETE CASCADE NOT NULL,
  show_name TEXT NOT NULL,
  season INTEGER NOT NULL,
  streaming_service TEXT NOT NULL,
  review TEXT NOT NULL,
  rating INTEGER NOT NULL
);